In [1]:
#Task: Cuisine Classification we have to classify restaurants based on their cuisines

#Objective: Develop a machine learning model to classify restaurants based on their cuisines.

In [2]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
#LOAD THE DATASET (RESTAURANT DATASET PROVIDED BY COGNIFYZ TECHNOLOGIES)

In [4]:
df = pd.read_csv('D:\Datasets/intern.csv')
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [6]:
df.shape

(9551, 21)

In [7]:
# Columns to drop
columns_to_drop = ['City', 'Address','Locality','Locality Verbose','Longitude','Latitude']

df = df.drop(columns=columns_to_drop)
df.head()

,Restaurant ID,Restaurant Name,Country Code,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,"French, Japanese, Desserts",1100,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Japanese,1200,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,"Japanese, Sushi",1500,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,"Japanese, Korean",1500,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [8]:
#CHECKING IF THERE ARE ANY NULL OR MISSING VALUES IN THE DATASET

In [9]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [ ]:
df = df.dropna()
df.isnull().sum()

NameError: name 'df' is not defined

In [11]:
#THERE ARE NO MISSING VALUES IN THE DATASET

In [12]:
#LET US DO SOME STATISTICAL TECHNIQUES ON THE DATASET

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9542 entries, 0 to 9550
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9542 non-null   int64
 1   Restaurant Name       9542 non-null   object
 2   Country Code          9542 non-null   int64
 3   Cuisines              9542 non-null   object
 4   Average Cost for two  9542 non-null   int64
 5   Currency              9542 non-null   object
 6   Has Table booking     9542 non-null   object
 7   Has Online delivery   9542 non-null   object
 8   Is delivering now     9542 non-null   object
 9   Switch to order menu  9542 non-null   object
 10  Price range           9542 non-null   int64
 11  Aggregate rating      9542 non-null   float64
 12  Rating color          9542 non-null   object
 13  Rating text           9542 non-null   object
 14  Votes                 9542 non-null   int64
dtypes: float64(1), int64(5), object(9)
memory usage: 1.2+ MB

In [14]:
df.describe()

,Restaurant ID,Country Code,Average Cost for two,Price range,Aggregate rating,Votes
count,9.542000e+03,9542.000000,9542.000000,9542.000000,9542.000000,9542.000000
mean,9.043301e+06,18.179208,1200.326137,1.804968,2.665238,156.772060
std,8.791967e+06,56.451600,16128.743876,0.905563,1.516588,430.203324
min,5.300000e+01,1.000000,0.000000,1.000000,0.000000,0.000000
25%,3.019312e+05,1.000000,250.000000,1.000000,2.500000,5.000000
50%,6.002726e+06,1.000000,400.000000,2.000000,3.200000,31.000000
75%,1.835260e+07,1.000000,700.000000,2.000000,3.700000,130.000000
max,1.850065e+07,216.000000,800000.000000,4.000000,4.900000,10934.000000

In [15]:
#WE HAVE TO CHANGE THE CATEGORICAL VARIABLES INTO NUMERIC USING LABELENCODER,ONE-HOT ENCODER,ORDINALENCODER

In [16]:
#LABEL ENCODING

from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
df['Switch to order menu'] = labelencoder.fit_transform(df['Switch to order menu'])
df['Has Table booking'] = labelencoder.fit_transform(df['Has Table booking'])
df['Has Online delivery'] = labelencoder.fit_transform(df['Has Online delivery'])
df['Is delivering now'] = labelencoder.fit_transform(df['Is delivering now'])
df.head()

,Restaurant ID,Restaurant Name,Country Code,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,"French, Japanese, Desserts",1100,Botswana Pula(P),1,0,0,0,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Japanese,1200,Botswana Pula(P),1,0,0,0,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),1,0,0,0,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,"Japanese, Sushi",1500,Botswana Pula(P),0,0,0,0,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,"Japanese, Korean",1500,Botswana Pula(P),1,0,0,0,4,4.8,Dark Green,Excellent,229

In [17]:
df.Cuisines

0             French, Japanese, Desserts
1                               Japanese
2       Seafood, Asian, Filipino, Indian
3                        Japanese, Sushi
4                       Japanese, Korean
                      ...
9546                             Turkish
9547     World Cuisine, Patisserie, Cafe
9548              Italian, World Cuisine
9549                     Restaurant Cafe
9550                                Cafe
Name: Cuisines, Length: 9542, dtype: object

In [18]:
#ORDINAL ENCODING FOR RATING COLOR COLUMN

from sklearn.preprocessing import OrdinalEncoder
ordinalencoder = OrdinalEncoder(categories=[['Orange', 'White', 'Yellow','Green','Dark Green','Red']])
df['Rating color'] = ordinalencoder.fit_transform(df[['Rating color']])
df.head()

,Restaurant ID,Restaurant Name,Country Code,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,"French, Japanese, Desserts",1100,Botswana Pula(P),1,0,0,0,3,4.8,4.0,Excellent,314
1,6304287,Izakaya Kikufuji,162,Japanese,1200,Botswana Pula(P),1,0,0,0,3,4.5,4.0,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),1,0,0,0,4,4.4,3.0,Very Good,270
3,6318506,Ooma,162,"Japanese, Sushi",1500,Botswana Pula(P),0,0,0,0,4,4.9,4.0,Excellent,365
4,6314302,Sambo Kojin,162,"Japanese, Korean",1500,Botswana Pula(P),1,0,0,0,4,4.8,4.0,Excellent,229

In [19]:
#ORDINAL ENCODING FOR RATING TEXT COLUMN
ordinalencoder = OrdinalEncoder(categories=[['Not rated','Poor','Average','Good','Very Good','Excellent']])
df['Rating text'] = ordinalencoder.fit_transform(df[['Rating text']])
df.head()

,Restaurant ID,Restaurant Name,Country Code,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,"French, Japanese, Desserts",1100,Botswana Pula(P),1,0,0,0,3,4.8,4.0,5.0,314
1,6304287,Izakaya Kikufuji,162,Japanese,1200,Botswana Pula(P),1,0,0,0,3,4.5,4.0,5.0,591
2,6300002,Heat - Edsa Shangri-La,162,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),1,0,0,0,4,4.4,3.0,4.0,270
3,6318506,Ooma,162,"Japanese, Sushi",1500,Botswana Pula(P),0,0,0,0,4,4.9,4.0,5.0,365
4,6314302,Sambo Kojin,162,"Japanese, Korean",1500,Botswana Pula(P),1,0,0,0,4,4.8,4.0,5.0,229

In [20]:
#I AM USING MINMAX SCALAR TO SCALE THE VALUES BETWEEN 0 AND 1 (MINMAX NORMALIZATION)

from sklearn.preprocessing import MinMaxScaler
minmax_scaler = MinMaxScaler()
df[['Country Code','Average Cost for two']] = minmax_scaler.fit_transform(df[['Country Code','Average Cost for two']])
df.head()

,Restaurant ID,Restaurant Name,Country Code,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,0.748837,"French, Japanese, Desserts",0.001375,Botswana Pula(P),1,0,0,0,3,4.8,4.0,5.0,314
1,6304287,Izakaya Kikufuji,0.748837,Japanese,0.001500,Botswana Pula(P),1,0,0,0,3,4.5,4.0,5.0,591
2,6300002,Heat - Edsa Shangri-La,0.748837,"Seafood, Asian, Filipino, Indian",0.005000,Botswana Pula(P),1,0,0,0,4,4.4,3.0,4.0,270
3,6318506,Ooma,0.748837,"Japanese, Sushi",0.001875,Botswana Pula(P),0,0,0,0,4,4.9,4.0,5.0,365
4,6314302,Sambo Kojin,0.748837,"Japanese, Korean",0.001875,Botswana Pula(P),1,0,0,0,4,4.8,4.0,5.0,229

In [21]:
#USING ONE HOT ENCODING (DUMMIES)

df_dummies = pd.get_dummies(df, columns=['Restaurant Name','Currency'], drop_first=True)
df_dummies.head()

,Restaurant ID,Country Code,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,...,Currency_Dollar($),Currency_Emirati Diram(AED),Currency_Indian Rupees(Rs.),Currency_Indonesian Rupiah(IDR),Currency_NewZealand($),Currency_Pounds(ï¿½ï¿½),Currency_Qatari Rial(QR),Currency_Rand(R),Currency_Sri Lankan Rupee(LKR),Currency_Turkish Lira(TL)
0,6317637,0.748837,"French, Japanese, Desserts",0.001375,1,0,0,0,3,4.8,...,False,False,False,False,False,False,False,False,False,False
1,6304287,0.748837,Japanese,0.001500,1,0,0,0,3,4.5,...,False,False,False,False,False,False,False,False,False,False
2,6300002,0.748837,"Seafood, Asian, Filipino, Indian",0.005000,1,0,0,0,4,4.4,...,False,False,False,False,False,False,False,False,False,False
3,6318506,0.748837,"Japanese, Sushi",0.001875,0,0,0,0,4,4.9,...,False,False,False,False,False,False,False,False,False,False
4,6314302,0.748837,"Japanese, Korean",0.001875,1,0,0,0,4,4.8,...,False,False,False,False,False,False,False,False,False,False

In [22]:
#CONVERTING TRUE AND FALSE TO 1 AND 0 RESPECTIVELY

df_numeric = df_dummies *1
df_numeric

,Restaurant ID,Country Code,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,...,Currency_Dollar($),Currency_Emirati Diram(AED),Currency_Indian Rupees(Rs.),Currency_Indonesian Rupiah(IDR),Currency_NewZealand($),Currency_Pounds(ï¿½ï¿½),Currency_Qatari Rial(QR),Currency_Rand(R),Currency_Sri Lankan Rupee(LKR),Currency_Turkish Lira(TL)
0,6317637,0.748837,"French, Japanese, Desserts",0.001375,1,0,0,0,3,4.8,...,0,0,0,0,0,0,0,0,0,0
1,6304287,0.748837,Japanese,0.001500,1,0,0,0,3,4.5,...,0,0,0,0,0,0,0,0,0,0
2,6300002,0.748837,"Seafood, Asian, Filipino, Indian",0.005000,1,0,0,0,4,4.4,...,0,0,0,0,0,0,0,0,0,0
3,6318506,0.748837,"Japanese, Sushi",0.001875,0,0,0,0,4,4.9,...,0,0,0,0,0,0,0,0,0,0
4,6314302,0.748837,"Japanese, Korean",0.001875,1,0,0,0,4,4.8,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,0.962791,Turkish,0.000100,0,0,0,0,3,4.1,...,0,0,0,0,0,0,0,0,0,1
9547,5908749,0.962791,"World Cuisine, Patisserie, Cafe",0.000131,0,0,0,0,3,4.2,...,0,0,0,0,0,0,0,0,0,1
9548,5915807,0.962791,"Italian, World Cuisine",0.000213,0,0,0,0,4,3.7,...,0,0,0,0,0,0,0,0,0,1
9549,5916112,0.962791,Restaurant Cafe,0.000150,0,0,0,0,4,4.0,...,0,0,0,0,0,0,0,0,0,1
9550,5927402,0.962791,Cafe,0.000069,0,0,0,0,2,4.0,...,0,0,0,0,0,0,0,0,0,1

In [23]:
df_numeric.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9542 entries, 0 to 9550
Columns: 7460 entries, Restaurant ID to Currency_Turkish Lira(TL)
dtypes: float64(5), int32(7451), int64(3), object(1)
memory usage: 271.9+ MB

In [24]:
df_numeric['Cuisines'].value_counts()

Cuisines
North Indian                                             936
North Indian, Chinese                                    511
Chinese                                                  354
Fast Food                                                354
North Indian, Mughlai                                    334
                                                        ...
Bengali, Fast Food                                         1
North Indian, Rajasthani, Asian                            1
Chinese, Thai, Malaysian, Indonesian                       1
Bakery, Desserts, North Indian, Bengali, South Indian      1
Italian, World Cuisine                                     1
Name: count, Length: 1825, dtype: int64

In [25]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df_numeric['Cuisines'] = label_encoder.fit_transform(df_numeric['Cuisines'])
df_numeric.head()

,Restaurant ID,Country Code,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,...,Currency_Dollar($),Currency_Emirati Diram(AED),Currency_Indian Rupees(Rs.),Currency_Indonesian Rupiah(IDR),Currency_NewZealand($),Currency_Pounds(ï¿½ï¿½),Currency_Qatari Rial(QR),Currency_Rand(R),Currency_Sri Lankan Rupee(LKR),Currency_Turkish Lira(TL)
0,6317637,0.748837,920,0.001375,1,0,0,0,3,4.8,...,0,0,0,0,0,0,0,0,0,0
1,6304287,0.748837,1111,0.001500,1,0,0,0,3,4.5,...,0,0,0,0,0,0,0,0,0,0
2,6300002,0.748837,1671,0.005000,1,0,0,0,4,4.4,...,0,0,0,0,0,0,0,0,0,0
3,6318506,0.748837,1126,0.001875,0,0,0,0,4,4.9,...,0,0,0,0,0,0,0,0,0,0
4,6314302,0.748837,1122,0.001875,1,0,0,0,4,4.8,...,0,0,0,0,0,0,0,0,0,0

In [26]:
#defining feature and target
x = df_numeric.drop('Cuisines',axis=1)
y = df_numeric['Cuisines']

In [27]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [28]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [29]:
model.fit(x_train,y_train)

LogisticRegression()

In [30]:
y_pred = model.predict(x_test)

In [31]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report

# Calculate performance metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f} %")
print(f"Precision: {precision:.2f} %")
print(f"Recall: {recall:.2f} %")
print("Classification Report:\n", class_report)

Accuracy: 0.10 %
Precision: 0.01 %
Recall: 0.10 %
Classification Report:
               precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         3
          16       0.00      0.00      0.00         3
          18       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         1
          25       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         2
          35       0.00      0.00      0.00         2
          38       0.00      0.00      0.00         1
          41       0.00      0.00      0.00         1
          52       0.00      0.00      0.00         1
          54       0.00      0.00      0.00         4
          55       0.00      0.00      0.00         2
          58       0.00      0.00      0.00        16
          59       0.00      0.00      0.00         1
          63       0.00      0.00      0.00         1
          64       0.00      0.00      0.00         1
          71       0.00      0.00      0.00         1
          73       0.00      0.00      0.00         1
          74       0.00      0.00      0.00         1
          75       0.00      0.00      0.00         1
          76       0.00      0.00      0.00         1
          78       0.00      0.00      0.00         2
          79       0.00      0.00      0.00         1
          83       0.00      0.00      0.00         1
          84       0.00      0.00      0.00         1
          91       0.00      0.00      0.00         1
          92       0.00      0.00      0.00         1
          98       0.00      0.00      0.00         1
         102       0.00      0.00      0.00         1
         108       0.00      0.00      0.00         1
         115       0.00      0.00      0.00         3
         116       0.00      0.00      0.00         1
         118       0.00      0.00      0.00         1
         119       0.00      0.00      0.00         1
         121       0.00      0.00      0.00         2
         122       0.00      0.00      0.00         1
         124       0.00      0.00      0.00         2
         127       0.00      0.00      0.00         1
         141       0.00      0.00      0.00         1
         143       0.00      0.00      0.00         1
         147       0.00      0.00      0.00         1
         154       0.00      0.00      0.00         1
         156       0.00      0.00      0.00         1
         159       0.00      0.00      0.00         1
         168       0.00      0.00      0.00         2
         171       0.00      0.00      0.00         1
         172       0.00      0.00      0.00         1
         173       0.00      0.00      0.00         1
         177       0.00      0.00      0.00        33
         178       0.00      0.00      0.00         1
         180       0.00      0.00      0.00         1
         183       0.00      0.00      0.00         1
         184       0.00      0.00      0.00         2
         186       0.00      0.00      0.00        36
         191       0.00      0.00      0.00        13
         201       0.00      0.00      0.00        16
         204       0.00      0.00      0.00         1
         206       0.00      0.00      0.00         1
         211       0.00      0.00      0.00         3
         212       0.00      0.00      0.00         1
         217       0.00      0.00      0.00         2
         218       0.00      0.00      0.00         2
         220       0.00      0.00      0.00         1
         222       0.00      0.00      0.00         1
         225       0.00      0.00      0.00         1
         226       0.00      0.00      0.00         2
         228       0.00      0.00      0.00         1
         230       0.00      0.00      0.00         9
         233       0.00      0.00      0.00         3
         235       0.00      0.00      0.00         1
         243       0.00      0.00      0.00         8
         246       0.00      0.00      0.00         2
         249       0.00      0.00      0.00         6
         251       0.00      0.00      0.00         4
         255       0.00      0.00      0.00         2
         258       0.00      0.00      0.00         1
         259       0.00      0.00      0.00         1
         260       0.00      0.00      0.00         1
         267       0.00      0.00      0.00         1
         268       0.00      0.00      0.00         1
         269       0.00      0.00      0.00         1
         282       0.00      0.00      0.00         1
         288       0.00      0.00      0.00         1
         291       0.00      0.00      0.00         1
         292       0.00      0.00      0.00         1
         293       0.00      0.00      0.00         1
         294       0.00      0.00      0.00         2
         295       0.00      0.00      0.00         1
         298       0.00      0.00      0.00         1
         302       0.00      0.00      0.00         1
         306       0.00      0.00      0.00         1
         307       0.00      0.00      0.00        11
         308       0.00      0.00      0.00         1
         310       0.00      0.00      0.00        11
         314       0.00      0.00      0.00         1
         318       0.00      0.00      0.00         1
         329       0.00      0.00      0.00         1
         331       0.00      0.00      0.00        62
         342       0.00      0.00      0.00         1
         344       0.00      0.00      0.00         3
         345       0.00      0.00      0.00         1
         346       0.00      0.00      0.00         1
         347       0.00      0.00      0.00         1
         351       0.00      0.00      0.00         1
         355       0.00      0.00      0.00         1
         358       0.00      0.00      0.00         2
         361       0.00      0.00      0.00         1
         364       0.00      0.00      0.00         1
         370       0.00      0.00      0.00         2
         371       0.00      0.00      0.00         1
         377       0.00      0.00      0.00         1
         378       0.00      0.00      0.00         1
         379       0.00      0.00      0.00         1
         383       0.00      0.00      0.00         1
         388       0.00      0.00      0.00         1
         393       0.00      0.00      0.00         1
         398       0.00      0.00      0.00         1
         399       0.00      0.00      0.00         1
         400       0.00      0.00      0.00         4
         408       0.00      0.00      0.00         1
         410       0.00      0.00      0.00         1
         412       0.00      0.00      0.00         1
         414       0.00      0.00      0.00         1
         419       0.00      0.00      0.00         1
         420       0.00      0.00      0.00         1
         423       0.00      0.00      0.00         1
         426       0.00      0.00      0.00         1
         428       0.00      0.00      0.00         1
         434       0.00      0.00      0.00         1
         436       0.00      0.00      0.00         1
         437       0.00      0.00      0.00         1
         439       0.00      0.00      0.00         1
         444       0.00      0.00      0.00         1
         454       0.00      0.00      0.00         1
         458       0.00      0.00      0.00         1
         460       0.00      0.00      0.00         1
         462       0.00      0.00      0.00         1
         466       0.00      0.00      0.00         1
         467       0.00      0.00      0.00         1
         468       0.00      0.00      0.00         1
         469       0.00      0.00      0.00         1
         473       0.00      0.00      0.00         1
         475       0.00      0.00      0.00         1
         487       0.00      0.00      0.00         3
         490       0.00      0.00      0.00         1
         492       0.00      0.00      0.00         1
         497       0.00      0.00      0.00        63
         502       0.00      0.00      0.00         1
         505       0.00      0.00      0.00         1
         507       0.00      0.00      0.00         1
         509       0.00      0.00      0.00         1
         512       0.00      0.00      0.00         1
         515       0.00      0.00      0.00         1
         518       0.00      0.00      0.00        31
         519       0.00      0.00      0.00         1
         520       0.00      0.00      0.00         1
         529       0.00      0.00      0.00         1
         530       0.00      0.00      0.00         1
         531       0.00      0.00      0.00         2
         541       0.00      0.00      0.00         1
         545       0.00      0.00      0.00         1
         546       0.00      0.00      0.00         1
         548       0.00      0.00      0.00         1
         549       0.00      0.00      0.00        16
         555       0.00      0.00      0.00         2
         557       0.00      0.00      0.00         1
         559       0.00      0.00      0.00         1
         562       0.00      0.00      0.00         1
         564       0.00      0.00      0.00         2
         565       0.00      0.00      0.00         1
         568       0.00      0.00      0.00         1
         572       0.00      0.00      0.00         1
         575       0.00      0.00      0.00         2
         576       0.00      0.00      0.00         1
         578       0.00      0.00      0.00         1
         582       0.00      0.00      0.00         2
         583       0.00      0.00      0.00         1
         584       0.00      0.00      0.00         2
         586       0.00      0.00      0.00         1
         587       0.00      0.00      0.00         1
         588       0.00      0.00      0.00        12
         589       0.00      0.00      0.00         5
         591       0.00      0.00      0.00         1
         596       0.00      0.00      0.00         2
         602       0.00      0.00      0.00         1
         603       0.00      0.00      0.00         1
         604       0.00      0.00      0.00         1
         607       0.00      0.00      0.00         1
         610       0.00      0.00      0.00         1
         613       0.00      0.00      0.00         1
         625       0.00      0.00      0.00         2
         626       0.00      0.00      0.00         3
         627       0.00      0.00      0.00         1
         628       0.00      0.00      0.00         1
         630       0.00      0.00      0.00         1
         637       0.00      0.00      0.00         1
         643       0.00      0.00      0.00         1
         650       0.00      0.00      0.00         1
         651       0.00      0.00      0.00         1
         654       0.00      0.00      0.00         1
         658       0.00      0.00      0.00         1
         664       0.00      0.00      0.00         1
         670       0.00      0.00      0.00         1
         674       0.00      0.00      0.00         1
         676       0.00      0.00      0.00         1
         677       0.00      0.00      0.00         1
         681       0.00      0.00      0.00         1
         682       0.00      0.00      0.00         1
         684       0.00      0.00      0.00         2
         689       0.00      0.00      0.00         1
         701       0.00      0.00      0.00         1
         703       0.00      0.00      0.00         1
         713       0.00      0.00      0.00         1
         716       0.00      0.00      0.00         1
         719       0.00      0.00      0.00         1
         721       0.00      0.00      0.00         1
         722       0.00      0.00      0.00         3
         724       0.00      0.00      0.00         1
         725       0.00      0.00      0.00         1
         732       0.00      0.00      0.00         1
         733       0.00      0.00      0.00         1
         736       0.00      0.00      0.00         2
         742       0.00      0.00      0.00         1
         744       0.00      0.00      0.00         1
         746       0.00      0.00      0.00         1
         754       0.00      0.00      0.00         1
         758       0.00      0.00      0.00        12
         759       0.00      0.00      0.00         1
         760       0.00      0.00      0.00         2
         761       0.00      0.00      0.00         3
         767       0.00      0.00      0.00         1
         770       0.00      0.00      0.00         1
         774       0.00      0.00      0.00         2
         779       0.00      0.00      0.00         1
         784       0.00      0.00      0.00         1
         785       0.00      0.00      0.00         1
         788       0.00      0.00      0.00         1
         791       0.00      0.00      0.00         2
         796       0.00      0.00      0.00         1
         802       0.00      0.00      0.00         1
         806       0.00      0.00      0.00         1
         808       0.00      0.00      0.00         1
         811       0.00      0.00      0.00         1
         818       0.00      0.00      0.00         1
         824       0.00      0.00      0.00         1
         825       0.00      0.00      0.00         1
         828       0.00      0.00      0.00        77
         833       0.00      0.00      0.00         1
         834       0.00      0.00      0.00         6
         837       0.00      0.00      0.00        12
         841       0.00      0.00      0.00         7
         842       0.00      0.00      0.00         1
         849       0.00      0.00      0.00         2
         850       0.00      0.00      0.00         1
         856       0.00      0.00      0.00         1
         859       0.00      0.00      0.00         4
         865       0.00      0.00      0.00        11
         868       0.00      0.00      0.00         3
         869       0.00      0.00      0.00         1
         870       0.00      0.00      0.00         1
         871       0.00      0.00      0.00         1
         878       0.00      0.00      0.00         2
         879       0.00      0.00      0.00         1
         880       0.00      0.00      0.00         1
         884       0.00      0.00      0.00         1
         885       0.00      0.00      0.00         1
         886       0.00      0.00      0.00         2
         887       0.00      0.00      0.00         2
         890       0.00      0.00      0.00         1
         892       0.00      0.00      0.00         1
         894       0.00      0.00      0.00         2
         895       0.00      0.00      0.00         9
         897       0.00      0.00      0.00         1
         898       0.00      0.00      0.00         1
         899       0.00      0.00      0.00         1
         903       0.00      0.00      0.00         1
         905       0.00      0.00      0.00         1
         908       0.00      0.00      0.00         2
         909       0.00      0.00      0.00         2
         910       0.00      0.00      0.00         1
         916       0.00      0.00      0.00         1
         920       0.00      0.00      0.00         1
         922       0.00      0.00      0.00         1
         924       0.00      0.00      0.00         1
         928       0.00      0.00      0.00         1
         931       0.00      0.00      0.00         1
         932       0.00      0.00      0.00         1
         934       0.00      0.00      0.00         1
         940       0.00      0.00      0.00         1
         944       0.00      0.00      0.00         1
         945       0.00      0.00      0.00         1
         946       0.00      0.00      0.00         1
         951       0.00      0.00      0.00         2
         956       0.00      0.00      0.00         1
         961       0.00      0.00      0.00         1
         962       0.00      0.00      0.00         1
         966       0.00      0.00      0.00         1
         968       0.00      0.00      0.00         1
         971       0.00      0.00      0.00         1
         972       0.00      0.00      0.00         1
         973       0.00      0.00      0.00         1
         982       0.00      0.00      0.00        14
         984       0.00      0.00      0.00         1
         986       0.00      0.00      0.00        17
         989       0.00      0.00      0.00         1
         995       0.00      0.00      0.00         2
        1001       0.00      0.00      0.00         1
        1002       0.00      0.00      0.00         1
        1006       0.00      0.00      0.00         1
        1010       0.00      0.00      0.00         1
        1011       0.00      0.00      0.00         1
        1017       0.00      0.00      0.00         1
        1018       0.00      0.00      0.00         1
        1019       0.00      0.00      0.00         1
        1021       0.00      0.00      0.00         1
        1022       0.00      0.00      0.00         2
        1031       0.00      0.00      0.00        15
        1035       0.00      0.00      0.00         1
        1043       0.00      0.00      0.00         1
        1044       0.00      0.00      0.00         1
        1047       0.00      0.00      0.00         1
        1051       0.00      0.00      0.00         1
        1052       0.00      0.00      0.00         1
        1056       0.00      0.00      0.00         1
        1058       0.00      0.00      0.00         1
        1065       0.00      0.00      0.00         2
        1069       0.00      0.00      0.00         1
        1076       0.00      0.00      0.00         1
        1090       0.00      0.00      0.00         1
        1091       0.00      0.00      0.00         1
        1092       0.00      0.00      0.00         1
        1093       0.00      0.00      0.00         1
        1098       0.00      0.00      0.00         3
        1099       0.00      0.00      0.00         1
        1101       0.00      0.00      0.00         1
        1102       0.00      0.00      0.00         8
        1111       0.00      0.00      0.00         2
        1116       0.00      0.00      0.00         1
        1118       0.00      0.00      0.00         1
        1122       0.00      0.00      0.00         1
        1125       0.00      0.00      0.00         2
        1126       0.00      0.00      0.00         4
        1129       0.00      0.00      0.00         1
        1138       0.00      0.00      0.00         1
        1141       0.00      0.00      0.00         1
        1142       0.00      0.00      0.00         2
        1151       0.00      0.00      0.00         1
        1153       0.00      0.00      0.00         1
        1161       0.00      0.00      0.00         1
        1164       0.00      0.00      0.00         1
        1167       0.00      0.00      0.00         1
        1170       0.00      0.00      0.00         3
        1178       0.00      0.00      0.00         1
        1179       0.00      0.00      0.00         1
        1181       0.00      0.00      0.00         1
        1185       0.00      0.00      0.00         1
        1186       0.00      0.00      0.00         1
        1192       0.00      0.00      0.00         1
        1193       0.00      0.00      0.00         1
        1202       0.00      0.00      0.00         1
        1203       0.00      0.00      0.00         1
        1204       0.00      0.00      0.00         1
        1205       0.00      0.00      0.00         2
        1211       0.00      0.00      0.00         1
        1212       0.00      0.00      0.00         7
        1214       0.00      0.00      0.00         1